


CREATE VIEW SarsopLogSummTimeView AS
select *, initTotalT_avg+lbBackT_avg+ubBackT_avg+sampleT_avg+pruneT_avg as subTotalT, 
	if(Info='online_T300_grx','online_T300_grx',if(Info like 'online_T300%','online_T300',Info)) as Info2
	from SarsopLogSumm



CREATE VIEW SarsopLogSummView AS
select  p.mapID,p.mapSize,p.reward,p.segmentX,p.segmentY,p.maxDepth,p.maxDepthFilter, t.*, elepsedT_avg-subTotalT as elapsedSubTtotalDiff, initTotalT_avg/subTotalT as initTotalTperc, lbBackT_avg/subTotalT as lbBackTperc,
	ubBackT_avg/subTotalT as ubBackTperc, sampleT_avg/subTotalT as sampleTperc, pruneT_avg/subTotalT as pruneTperc
from SarsopLogSummTimeView t left join SarsopLogFileParams p on t.FileName=p.FileName;




CREATE TABLE SarsopLogFileParams (
	FileName varchar(255),
	mapID int,
	mapSize varchar(25),
	reward varchar(100),
	segmentX varchar(25),
	segmentY varchar(25),
	maxDepth varchar(25),
	maxDepthFilter varchar(5)
);



INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew.txt',1,'10x10','triangle','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gc.txt',1,'10x10','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gc_grx_1c.txt',1,'10x10','triangle','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gc_maxd100.txt',1,'10x10','triangle','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gc_maxd20.txt',1,'10x10','triangle','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gc_maxd50.txt',1,'10x10','triangle','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gc_sh.txt',1,'10x10','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gc_sh_2c.txt',1,'10x10','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gc_sh_grx_1c.txt',1,'10x10','triangle','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gc_sh_maxd100.txt',1,'10x10','triangle','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gc_sh_maxd20.txt',1,'10x10','triangle','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gr.txt',1,'10x10','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gr_grx_1c.txt',1,'10x10','triangle','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gr_maxd100.txt',1,'10x10','triangle','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gr_maxd20.txt',1,'10x10','triangle','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gr_maxd50.txt',1,'10x10','triangle','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gr_sh.txt',1,'10x10','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gr_sh_2c.txt',1,'10x10','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gr_sh_grx_1c.txt',1,'10x10','triangle','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gr_sh_maxd100.txt',1,'10x10','triangle','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_newrew_on_gr_sh_maxd20.txt',1,'10x10','triangle','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_srw_fs.txt',1,'10x10','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_srw_fsc.txt',1,'10x10','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gc.txt',1,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gc_grx_1c.txt',1,'10x10','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gc_maxd100.txt',1,'10x10','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gc_maxd20.txt',1,'10x10','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gc_maxd50.txt',1,'10x10','final cross','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gc_sh.txt',1,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gc_sh_2c.txt',1,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gc_sh_grx_1c.txt',1,'10x10','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gc_sh_maxd100.txt',1,'10x10','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gc_sh_maxd20.txt',1,'10x10','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gr.txt',1,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gr_grx_1c.txt',1,'10x10','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gr_maxd100.txt',1,'10x10','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gr_maxd20.txt',1,'10x10','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gr_maxd50.txt',1,'10x10','final cross','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gr_sh.txt',1,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gr_sh_2c.txt',1,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gr_sh_grx_1c.txt',1,'10x10','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gr_sh_maxd100.txt',1,'10x10','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fsc_on_gr_sh_maxd20.txt',1,'10x10','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gc.txt',1,'10x10','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gc_grx_1c.txt',1,'10x10','final','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gc_maxd100.txt',1,'10x10','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gc_maxd20.txt',1,'10x10','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gc_maxd50.txt',1,'10x10','final','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gc_sh.txt',1,'10x10','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gc_sh_2c.txt',1,'10x10','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gc_sh_grx_1c.txt',1,'10x10','final','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gc_sh_maxd100.txt',1,'10x10','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gc_sh_maxd20.txt',1,'10x10','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gr.txt',1,'10x10','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gr_grx_1c.txt',1,'10x10','final','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gr_maxd100.txt',1,'10x10','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gr_maxd20.txt',1,'10x10','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gr_maxd3.txt',1,'10x10','final','rc','none','3','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gr_maxd50.txt',1,'10x10','final','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gr_sh.txt',1,'10x10','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gr_sh_2c.txt',1,'10x10','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gr_sh_grx_1c.txt',1,'10x10','final','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gr_sh_maxd100.txt',1,'10x10','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_10x10_sr_fs_on_gr_sh_maxd20.txt',1,'10x10','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_srw_fs.txt',1,'12x12','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_srw_fsc.txt',1,'12x12','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gc.txt',1,'12x12','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gc_maxd100.txt',1,'12x12','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gc_maxd20.txt',1,'12x12','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gc_maxd50.txt',1,'12x12','final cross','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gc_sh.txt',1,'12x12','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gc_sh_2c.txt',1,'12x12','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gc_sh_grx_1c.txt',1,'12x12','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gc_sh_maxd100.txt',1,'12x12','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gc_sh_maxd20.txt',1,'12x12','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gr.txt',1,'12x12','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gr_maxd100.txt',1,'12x12','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gr_maxd20.txt',1,'12x12','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gr_maxd50.txt',1,'12x12','final cross','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gr_sh.txt',1,'12x12','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gr_sh_2c.txt',1,'12x12','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gr_sh_grx_1c.txt',1,'12x12','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gr_sh_maxd100.txt',1,'12x12','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fsc_on_gr_sh_maxd20.txt',1,'12x12','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gc.txt',1,'12x12','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gc_maxd100.txt',1,'12x12','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gc_maxd20.txt',1,'12x12','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gc_maxd50.txt',1,'12x12','final','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gc_sh.txt',1,'12x12','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gc_sh_2c.txt',1,'12x12','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gc_sh_grx_1c.txt',1,'12x12','final','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gc_sh_maxd100.txt',1,'12x12','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gc_sh_maxd20.txt',1,'12x12','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gr.txt',1,'12x12','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gr_maxd100.txt',1,'12x12','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gr_maxd20.txt',1,'12x12','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gr_maxd50.txt',1,'12x12','final','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gr_sh.txt',1,'12x12','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gr_sh_2c.txt',1,'12x12','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gr_sh_grx_1c.txt',1,'12x12','final','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gr_sh_maxd100.txt',1,'12x12','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map1_12x12_sr_fs_on_gr_sh_maxd20.txt',1,'12x12','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gc.txt',2,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gc_grx_1c.txt',2,'10x10','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gc_maxd100.txt',2,'10x10','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gc_maxd20.txt',2,'10x10','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gc_maxd50.txt',2,'10x10','final cross','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gc_sh.txt',2,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gc_sh_2c.txt',2,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gc_sh_grx_1c.txt',2,'10x10','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gc_sh_maxd100.txt',2,'10x10','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gc_sh_maxd20.txt',2,'10x10','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gr.txt',2,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gr_grx_1c.txt',2,'10x10','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gr_maxd100.txt',2,'10x10','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gr_maxd20.txt',2,'10x10','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gr_maxd50.txt',2,'10x10','final cross','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gr_sh.txt',2,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gr_sh_2c.txt',2,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gr_sh_grx_1c.txt',2,'10x10','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gr_sh_maxd100.txt',2,'10x10','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_10x10_sr_fsc_on_gr_sh_maxd20.txt',2,'10x10','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_srw_fs.txt',2,'12x12','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_srw_fsc.txt',2,'12x12','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gc.txt',2,'12x12','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gc_maxd100.txt',2,'12x12','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gc_maxd20.txt',2,'12x12','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gc_maxd50.txt',2,'12x12','final cross','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gc_sh.txt',2,'12x12','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gc_sh_2c.txt',2,'12x12','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gc_sh_grx_1c.txt',2,'12x12','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gc_sh_maxd100.txt',2,'12x12','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gc_sh_maxd20.txt',2,'12x12','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gr.txt',2,'12x12','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gr_maxd100.txt',2,'12x12','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gr_maxd20.txt',2,'12x12','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gr_maxd50.txt',2,'12x12','final cross','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gr_sh.txt',2,'12x12','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gr_sh_2c.txt',2,'12x12','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gr_sh_grx_1c.txt',2,'12x12','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gr_sh_maxd100.txt',2,'12x12','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fsc_on_gr_sh_maxd20.txt',2,'12x12','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gc.txt',2,'12x12','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gc_maxd100.txt',2,'12x12','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gc_maxd20.txt',2,'12x12','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gc_maxd50.txt',2,'12x12','final','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gc_sh.txt',2,'12x12','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gc_sh_2c.txt',2,'12x12','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gc_sh_grx_1c.txt',2,'12x12','final','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gc_sh_maxd100.txt',2,'12x12','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gc_sh_maxd20.txt',2,'12x12','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gr.txt',2,'12x12','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gr_maxd100.txt',2,'12x12','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gr_maxd20.txt',2,'12x12','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gr_maxd50.txt',2,'12x12','final','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gr_sh.txt',2,'12x12','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gr_sh_2c.txt',2,'12x12','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gr_sh_grx_1c.txt',2,'12x12','final','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gr_sh_maxd100.txt',2,'12x12','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_12x12_sr_fs_on_gr_sh_maxd20.txt',2,'12x12','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_6x5_newrew.txt',2,'6x5','triangle','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_6x5_srw_fs.txt',2,'6x5','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map2_6x5_srw_fsc.txt',2,'6x5','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew.txt',3,'10x10','triangle','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gc.txt',3,'10x10','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gc_grx_1c.txt',3,'10x10','triangle','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gc_maxd10.txt',3,'10x10','triangle','rcc','none','10','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gc_maxd100.txt',3,'10x10','triangle','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gc_maxd20.txt',3,'10x10','triangle','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gc_maxd50.txt',3,'10x10','triangle','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gc_sh.txt',3,'10x10','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gc_sh_2c.txt',3,'10x10','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gc_sh_grx_1c.txt',3,'10x10','triangle','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gc_sh_maxd100.txt',3,'10x10','triangle','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gc_sh_maxd20.txt',3,'10x10','triangle','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gr.txt',3,'10x10','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gr_grx_1c.txt',3,'10x10','triangle','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gr_maxd100.txt',3,'10x10','triangle','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gr_maxd20.txt',3,'10x10','triangle','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gr_maxd50.txt',3,'10x10','triangle','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gr_sh.txt',3,'10x10','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gr_sh_2c.txt',3,'10x10','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gr_sh_grx_1c.txt',3,'10x10','triangle','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gr_sh_maxd10.txt',3,'10x10','triangle','rc','none','10','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gr_sh_maxd100.txt',3,'10x10','triangle','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_newrew_on_gr_sh_maxd20.txt',3,'10x10','triangle','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_srw_fs.txt',3,'10x10','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_srw_fsc.txt',3,'10x10','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gc.txt',3,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gc_grx_1c.txt',3,'10x10','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gc_maxd100.txt',3,'10x10','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gc_maxd20.txt',3,'10x10','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gc_maxd50.txt',3,'10x10','final cross','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gc_sh.txt',3,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gc_sh_2c.txt',3,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gc_sh_grx_1c.txt',3,'10x10','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gc_sh_maxd100.txt',3,'10x10','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gc_sh_maxd20.txt',3,'10x10','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gr.txt',3,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gr_grx_1c.txt',3,'10x10','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gr_maxd100.txt',3,'10x10','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gr_maxd20.txt',3,'10x10','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gr_maxd50.txt',3,'10x10','final cross','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gr_sh.txt',3,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gr_sh_2c.txt',3,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gr_sh_grx_1c.txt',3,'10x10','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gr_sh_maxd100.txt',3,'10x10','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fsc_on_gr_sh_maxd20.txt',3,'10x10','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gc.txt',3,'10x10','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gc_grx_1c.txt',3,'10x10','final','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gc_maxd100.txt',3,'10x10','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gc_maxd20.txt',3,'10x10','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gc_maxd50.txt',3,'10x10','final','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gc_sh.txt',3,'10x10','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gc_sh_2c.txt',3,'10x10','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gc_sh_grx_1c.txt',3,'10x10','final','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gc_sh_maxd100.txt',3,'10x10','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gc_sh_maxd20.txt',3,'10x10','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gr.txt',3,'10x10','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gr_grx_1c.txt',3,'10x10','final','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gr_maxd100.txt',3,'10x10','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gr_maxd20.txt',3,'10x10','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gr_maxd50.txt',3,'10x10','final','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gr_sh.txt',3,'10x10','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gr_sh_2c.txt',3,'10x10','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gr_sh_grx_1c.txt',3,'10x10','final','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gr_sh_maxd100.txt',3,'10x10','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_10x10_sr_fs_on_gr_sh_maxd20.txt',3,'10x10','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_srw_fs.txt',3,'12x12','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_srw_fsc.txt',3,'12x12','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gc.txt',3,'12x12','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gc_maxd10.txt',3,'12x12','final cross','rcc','none','10','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gc_maxd100.txt',3,'12x12','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gc_maxd20.txt',3,'12x12','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gc_maxd50.txt',3,'12x12','final cross','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gc_sh.txt',3,'12x12','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gc_sh_2c.txt',3,'12x12','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gc_sh_grx_1c.txt',3,'12x12','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gc_sh_maxd10.txt',3,'12x12','final cross','rcc','none','10','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gc_sh_maxd100.txt',3,'12x12','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gc_sh_maxd20.txt',3,'12x12','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gr.txt',3,'12x12','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gr_maxd100.txt',3,'12x12','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gr_maxd20.txt',3,'12x12','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gr_maxd50.txt',3,'12x12','final cross','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gr_sh.txt',3,'12x12','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gr_sh_2c.txt',3,'12x12','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gr_sh_grx_1c.txt',3,'12x12','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gr_sh_maxd100.txt',3,'12x12','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fsc_on_gr_sh_maxd20.txt',3,'12x12','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gc.txt',3,'12x12','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gc_maxd10.txt',3,'12x12','final','rcc','none','10','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gc_maxd100.txt',3,'12x12','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gc_maxd20.txt',3,'12x12','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gc_maxd50.txt',3,'12x12','final','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gc_sh.txt',3,'12x12','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gc_sh_2c.txt',3,'12x12','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gc_sh_grx_1c.txt',3,'12x12','final','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gc_sh_maxd100.txt',3,'12x12','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gc_sh_maxd20.txt',3,'12x12','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gr.txt',3,'12x12','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gr_maxd100.txt',3,'12x12','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gr_maxd20.txt',3,'12x12','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gr_maxd50.txt',3,'12x12','final','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gr_sh.txt',3,'12x12','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gr_sh_2c.txt',3,'12x12','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gr_sh_grx_1c.txt',3,'12x12','final','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gr_sh_maxd100.txt',3,'12x12','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_12x12_sr_fs_on_gr_sh_maxd20.txt',3,'12x12','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_15x15_srw_fs.txt',3,'15x15','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_15x15_srw_fsc.txt',3,'15x15','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_15x15_sr_fsc_on_gc.txt',3,'15x15','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_15x15_sr_fsc_on_gr.txt',3,'15x15','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_15x15_sr_fs_on_gc.txt',3,'15x15','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_15x15_sr_fs_on_gr.txt',3,'15x15','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_newrew.txt',3,'6x5','triangle','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_newrew_on_gc_sh.txt',3,'6x5','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_newrew_on_gc_sh_grx_1c.txt',3,'6x5','triangle','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_newrew_on_gc_sh_maxd100.txt',3,'6x5','triangle','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_newrew_on_gc_sh_maxd20.txt',3,'6x5','triangle','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_newrew_on_gr_sh.txt',3,'6x5','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_newrew_on_gr_sh_grx_1c.txt',3,'6x5','triangle','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_newrew_on_gr_sh_maxd100.txt',3,'6x5','triangle','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_newrew_on_gr_sh_maxd20.txt',3,'6x5','triangle','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_srw_fs.txt',3,'6x5','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_srw_fsc.txt',3,'6x5','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fsc_on_gc_sh.txt',3,'6x5','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fsc_on_gc_sh_grx_1c.txt',3,'6x5','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fsc_on_gc_sh_maxd100.txt',3,'6x5','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fsc_on_gc_sh_maxd20.txt',3,'6x5','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fsc_on_gr_sh.txt',3,'6x5','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fsc_on_gr_sh_grx_1c.txt',3,'6x5','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fsc_on_gr_sh_maxd100.txt',3,'6x5','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fsc_on_gr_sh_maxd20.txt',3,'6x5','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fs_on_gc_sh.txt',3,'6x5','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fs_on_gc_sh_grx_1c.txt',3,'6x5','final','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fs_on_gc_sh_maxd100.txt',3,'6x5','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fs_on_gc_sh_maxd20.txt',3,'6x5','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fs_on_gr_sh.txt',3,'6x5','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fs_on_gr_sh_grx_1c.txt',3,'6x5','final','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fs_on_gr_sh_maxd100.txt',3,'6x5','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map3_6x5_sr_fs_on_gr_sh_maxd20.txt',3,'6x5','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew.txt',4,'10x10','triangle','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gc.txt',4,'10x10','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gc_grx_1c.txt',4,'10x10','triangle','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gc_maxd100.txt',4,'10x10','triangle','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gc_maxd20.txt',4,'10x10','triangle','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gc_maxd50.txt',4,'10x10','triangle','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gc_sh.txt',4,'10x10','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gc_sh_2c.txt',4,'10x10','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gc_sh_grx_1c.txt',4,'10x10','triangle','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gc_sh_maxd100.txt',4,'10x10','triangle','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gc_sh_maxd20.txt',4,'10x10','triangle','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gr.txt',4,'10x10','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gr_grx_1c.txt',4,'10x10','triangle','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gr_maxd100.txt',4,'10x10','triangle','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gr_maxd20.txt',4,'10x10','triangle','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gr_maxd50.txt',4,'10x10','triangle','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gr_sh.txt',4,'10x10','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gr_sh_2c.txt',4,'10x10','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gr_sh_maxd100.txt',4,'10x10','triangle','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_newrew_on_gr_sh_maxd20.txt',4,'10x10','triangle','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_srw_fs.txt',4,'10x10','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_srw_fsc.txt',4,'10x10','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gc.txt',4,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gc_grx_1c.txt',4,'10x10','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gc_maxd100.txt',4,'10x10','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gc_maxd20.txt',4,'10x10','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gc_maxd50.txt',4,'10x10','final cross','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gc_sh.txt',4,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gc_sh_2c.txt',4,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gc_sh_grx_1c.txt',4,'10x10','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gc_sh_maxd100.txt',4,'10x10','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gc_sh_maxd20.txt',4,'10x10','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gr.txt',4,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gr_grx_1c.txt',4,'10x10','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gr_maxd100.txt',4,'10x10','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gr_maxd20.txt',4,'10x10','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gr_maxd50.txt',4,'10x10','final cross','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gr_sh.txt',4,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gr_sh_2c.txt',4,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gr_sh_grx_1c.txt',4,'10x10','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gr_sh_maxd100.txt',4,'10x10','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_10x10_sr_fsc_on_gr_sh_maxd20.txt',4,'10x10','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_srw_fs.txt',4,'12x12','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_srw_fsc.txt',4,'12x12','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gc.txt',4,'12x12','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gc_maxd100.txt',4,'12x12','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gc_maxd20.txt',4,'12x12','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gc_maxd50.txt',4,'12x12','final cross','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gc_sh.txt',4,'12x12','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gc_sh_2c.txt',4,'12x12','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gc_sh_grx_1c.txt',4,'12x12','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gc_sh_maxd100.txt',4,'12x12','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gc_sh_maxd20.txt',4,'12x12','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gr.txt',4,'12x12','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gr_maxd100.txt',4,'12x12','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gr_maxd20.txt',4,'12x12','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gr_maxd50.txt',4,'12x12','final cross','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gr_sh.txt',4,'12x12','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gr_sh_2c.txt',4,'12x12','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gr_sh_grx_1c.txt',4,'12x12','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gr_sh_maxd100.txt',4,'12x12','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fsc_on_gr_sh_maxd20.txt',4,'12x12','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gc.txt',4,'12x12','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gc_maxd100.txt',4,'12x12','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gc_maxd20.txt',4,'12x12','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gc_maxd50.txt',4,'12x12','final','rcc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gc_sh.txt',4,'12x12','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gc_sh_2c.txt',4,'12x12','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gc_sh_grx_1c.txt',4,'12x12','final','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gc_sh_maxd100.txt',4,'12x12','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gc_sh_maxd20.txt',4,'12x12','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gr.txt',4,'12x12','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gr_maxd100.txt',4,'12x12','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gr_maxd20.txt',4,'12x12','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gr_maxd50.txt',4,'12x12','final','rc','none','50','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gr_sh.txt',4,'12x12','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gr_sh_2c.txt',4,'12x12','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gr_sh_grx_1c.txt',4,'12x12','final','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gr_sh_maxd100.txt',4,'12x12','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_12x12_sr_fs_on_gr_sh_maxd20.txt',4,'12x12','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_15x15_srw_fs.txt',4,'15x15','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_15x15_srw_fsc.txt',4,'15x15','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_15x15_sr_fsc_on_gc.txt',4,'15x15','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_15x15_sr_fsc_on_gr.txt',4,'15x15','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_15x15_sr_fs_on_gc.txt',4,'15x15','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_15x15_sr_fs_on_gr.txt',4,'15x15','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_newrew.txt',4,'6x5','triangle','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_newrew_on_gc_sh.txt',4,'6x5','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_newrew_on_gc_sh_grx_1c.txt',4,'6x5','triangle','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_newrew_on_gc_sh_maxd100.txt',4,'6x5','triangle','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_newrew_on_gc_sh_maxd20.txt',4,'6x5','triangle','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_newrew_on_gr_sh.txt',4,'6x5','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_newrew_on_gr_sh_grx_1c.txt',4,'6x5','triangle','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_newrew_on_gr_sh_maxd100.txt',4,'6x5','triangle','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_newrew_on_gr_sh_maxd20.txt',4,'6x5','triangle','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_srw_fs.txt',4,'6x5','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_srw_fsc.txt',4,'6x5','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fsc_on_gc_sh.txt',4,'6x5','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fsc_on_gc_sh_grx_1c.txt',4,'6x5','final cross','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fsc_on_gc_sh_maxd100.txt',4,'6x5','final cross','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fsc_on_gc_sh_maxd20.txt',4,'6x5','final cross','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fsc_on_gr_sh.txt',4,'6x5','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fsc_on_gr_sh_grx_1c.txt',4,'6x5','final cross','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fsc_on_gr_sh_maxd100.txt',4,'6x5','final cross','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fsc_on_gr_sh_maxd20.txt',4,'6x5','final cross','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fs_on_gc_sh.txt',4,'6x5','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fs_on_gc_sh_grx_1c.txt',4,'6x5','final','rcc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fs_on_gc_sh_maxd100.txt',4,'6x5','final','rcc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fs_on_gc_sh_maxd20.txt',4,'6x5','final','rcc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fs_on_gr_sh.txt',4,'6x5','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fs_on_gr_sh_grx_1c.txt',4,'6x5','final','rc','rc','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fs_on_gr_sh_maxd100.txt',4,'6x5','final','rc','none','100','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map4_6x5_sr_fs_on_gr_sh_maxd20.txt',4,'6x5','final','rc','none','20','yes');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map5_6x5_newrew.txt',5,'6x5','triangle','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map5_6x5_srw_fs.txt',5,'6x5','final','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_map5_6x5_srw_fsc.txt',5,'6x5','final cross','none','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map1_10x10_newrew_on_gc.txt',1,'10x10','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map1_10x10_newrew_on_gr.txt',1,'10x10','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map1_10x10_sr_fsc_on_gc.txt',1,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map1_10x10_sr_fsc_on_gr.txt',1,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map1_10x10_sr_fs_on_gc.txt',1,'10x10','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map1_10x10_sr_fs_on_gr.txt',1,'10x10','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map2_6x5_newrew_on_gc.txt',2,'6x5','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map2_6x5_newrew_on_gr.txt',2,'6x5','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map2_6x5_sr_fsc_on_gc.txt',2,'6x5','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map2_6x5_sr_fsc_on_gr.txt',2,'6x5','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map2_6x5_sr_fs_on_gc.txt',2,'6x5','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map2_6x5_sr_fs_on_gr.txt',2,'6x5','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_10x10_newrew_on_gc.txt',3,'10x10','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_10x10_sr_fsc_on_gc.txt',3,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_10x10_sr_fs_on_gc.txt',3,'10x10','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_6x5_newrew_on_gc.txt',3,'6x5','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_6x5_newrew_on_gc.txt',3,'6x5','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_6x5_newrew_on_gr.txt',3,'6x5','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_6x5_newrew_on_gr.txt',3,'6x5','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_6x5_sr_fsc_on_gc.txt',3,'6x5','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_6x5_sr_fsc_on_gc.txt',3,'6x5','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_6x5_sr_fsc_on_gr.txt',3,'6x5','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_6x5_sr_fsc_on_gr.txt',3,'6x5','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_6x5_sr_fs_on_gc.txt',3,'6x5','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_6x5_sr_fs_on_gc.txt',3,'6x5','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_6x5_sr_fs_on_gr.txt',3,'6x5','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map3_6x5_sr_fs_on_gr.txt',3,'6x5','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_10x10_newrew_on_gc.txt',4,'10x10','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_10x10_newrew_on_gr.txt',4,'10x10','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_10x10_sr_fsc_on_gc.txt',4,'10x10','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_10x10_sr_fsc_on_gr.txt',4,'10x10','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_10x10_sr_fs_on_gc.txt',4,'10x10','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_10x10_sr_fs_on_gr.txt',4,'10x10','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_6x5_newrew_on_gc.txt',4,'6x5','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_6x5_newrew_on_gc.txt',4,'6x5','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_6x5_newrew_on_gr.txt',4,'6x5','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_6x5_newrew_on_gr.txt',4,'6x5','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_6x5_sr_fsc_on_gc.txt',4,'6x5','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_6x5_sr_fsc_on_gc.txt',4,'6x5','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_6x5_sr_fsc_on_gr.txt',4,'6x5','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_6x5_sr_fsc_on_gr.txt',4,'6x5','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_6x5_sr_fs_on_gc.txt',4,'6x5','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_6x5_sr_fs_on_gc.txt',4,'6x5','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_6x5_sr_fs_on_gr.txt',4,'6x5','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map4_6x5_sr_fs_on_gr.txt',4,'6x5','final','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map5_6x5_newrew_on_gc.txt',5,'6x5','triangle','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map5_6x5_newrew_on_gr.txt',5,'6x5','triangle','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map5_6x5_sr_fsc_on_gc.txt',5,'6x5','final cross','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map5_6x5_sr_fsc_on_gr.txt',5,'6x5','final cross','rc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map5_6x5_sr_fs_on_gc.txt',5,'6x5','final','rcc','none','none','no');
INSERT into SarsopLogFileParams values ('SARSOP_time_log_spd_map5_6x5_sr_fs_on_gr.txt',5,'6x5','final','rc','none','none','no');
