#include "hsglobaldata.h"

#ifdef USE_QT
const QStringList HSGlobalData::MAPS = QStringList()
                           << "map1_6x5_0o.txt"<<"map2_6x5_1o.txt"<<"map3_6x5_2o.txt"
                           << "map4_6x5_2o.txt"<<"map5_6x5_4o.txt"<< "map1_40x40_1o.txt"
                           << "map2_40x40_2o.txt"<< "map3_40x40_3o.txt"<< "map4_40x40_4o.txt"
                           << "map5_40x40_5o.txt"<< "testmapbig1.txt" << "testmapbig2.txt"
                           << "map1_10x10_1o.txt" << "map2_10x10_2o.txt" << "map3_10x10_3o.txt"
                           << "map4_10x10_4o.txt" << "map5_10x10.txt" << "map6_10x10.txt"
                           << "map7_10x10.txt"  << "mapbcn1.txt" << "mapbcn2.txt"
                           << "mapbcn3.txt" << "mapbcn1a.txt" << "mapbcn1b.txt"
                           << "mapbcn1c.txt" << "map1_20x20_0o.txt" << "map2_20x20_1o.txt"
                           << "map3_20x20_2o.txt" << "map4_20x20_3o.txt" << "map5_20x20_4o.txt"
                           << "map1_3x3_0o.txt" << "map2_3x3_1o.txt" << "map3_3x3_2o.txt"
                           << "map1_5x5_0o.txt" << "map2_5x5_1o.txt" << "map3_5x5_2o.txt"
                           << "map1_7x7_0o.txt" << "map2_7x7_1o.txt" << "map3_7x7_2o.txt"
                           // FROM HERE copied
                           << "map1_40x40.txt"
                           << "map2_40x40.txt"
                           << "map3_40x40.txt"
                           << "map4_40x40.txt"
                           << "map5_40x40.txt"
                           << "map1_20x20.txt"
                           << "map2_20x20.txt"
                           << "map3_20x20.txt"
                           << "map4_20x20.txt"
                           << "map5_20x20.txt"
                           << "map1_17x17.txt"
                           << "map2_17x17.txt"
                           << "map3_17x17.txt"
                           << "map4_17x17.txt"
                           << "map1_15x15.txt"
                           << "map2_15x15.txt"
                           << "map3_15x15.txt"
                           << "map4_15x15.txt"
                           << "map1_12x12.txt"
                           << "map2_12x12.txt"
                           << "map3_12x12.txt"
                           << "map4_12x12.txt"
                           << "map1_10x10.txt"
                           << "map2_10x10.txt"
                           << "map3_10x10.txt"
                           << "map4_10x10.txt"
                           << "map1_7x7.txt"
                           << "map2_7x7.txt"
                           << "map3_7x7.txt"
                           << "map1_6x5.txt"
                           << "map2_6x5.txt"
                           << "map3_6x5.txt"
                           << "map4_6x5.txt"
                           << "map5_6x5.txt"
                           << "map1_5x5.txt"
                           << "map2_5x5.txt"
                           << "map3_5x5.txt"
                           << "map1_3x3.txt"
                           << "map2_3x3.txt"
                           << "map3_3x3.txt"
                           << "fme_place/map1_10x12.txt"
                           << "fme_place/map1_12x14.txt"
                           << "fme_place/map2_10x12.txt"
                           << "fme_place/map2_12x14.txt"
                           << "fme_place/map3_10x12.txt"
                           << "fme_place/map3_12x14.txt"
                           << "fme_place/map_fmep1_10x12.txt"
                           << "fme_place/map_fmep1_12x14.txt"
                           << "fme_place/map_fmep2_10x12.txt"
                           << "fme_place/map_fmep2_12x14.txt"
                           << "fme_place/map_fmep3_10x12.txt"
                           << "fme_place/map_fmep3_12x14.txt"
                           << "map1_10x12.txt"
                           << "map1_12x14.txt"
                           << "map2_10x12.txt"
                           << "map2_12x14.txt"
                           << "map3_10x12.txt"
                           << "map3_12x14.txt"
                           << "fme_place/map1_9x10.txt"
                           << "fme_place/map2_9x10.txt"
                           << "fme_place/map3_9x10.txt"
                           << "map1_9x10.txt"
                           << "map2_9x10.txt"
                           << "map3_9x10.txt"
                           << "map0_8x6.txt"
                           << "map1_8x6.txt"
                           << "map0_6x8.txt"
                           << "map1_6x8.txt"
                           << "map0_7x9.txt"
                           << "map1_7x9.txt"
                           << "map2_7x9.txt"
                           << "map3_7x9.txt"
                           << "mapbcn_full.txt"
                           << "fme_place/map1_9x12.txt"
                           << "fme_place/map2_9x12.txt"
                           << "map1_9x12.txt"
                           << "map2_9x12.txt"
                           << "mapbcn4.txt"
                           << "mapbcn5.txt"
                           << "mapbcn6.txt";


//ACTIONS = [HALT_ACT; N_ACT; NE_ACT; E_ACT; SE_ACT; S_ACT; SW_ACT; W_ACT; NW_ACT];
const QStringList HSGlobalData::ACTIONS = QStringList()
        << "halt" << "north" << "north-east" << "east" << "south-east" << "south" << "south-west" << "west" << "north-west";

const QStringList HSGlobalData::ACTIONS_SHORT = QStringList()
        << "h" << "n" << "ne" << "e" << "se" << "s" << "sw" << "w" << "nw";

#endif
