-- table with constants
DROP TABLE IF EXISTS SolverType;
CREATE TABLE SolverType (
	id smallint(6) NOT NULL, PRIMARY KEY(id),
	Name VARCHAR(50),
    PubName VARCHAR(50) -- publication name
);

INSERT INTO SolverType VALUES  (0, 'Not Set', 							'Not Set'), 
						   	   (1, 'MOMDP Offline', 					'MOMDP Offline'), 
						   	   (2, 'MOMDP Layered', 					'MOMDP Layered'), 
						   	   (3, 'MOMDP Layered Compare', 			'MOMDP Layered Compare'), 
						   	   (4, 'MCVI Offline', 						'MCVI Offline'), 
						   	   (5, 'POMCP', 							'CR-POMCP'), 
						   	   (6, 'N/A',								'N/A'), 
						   	   (7, 'Follower LastPos',					'Follower LP'), 
						   	   (8, 'Follower',	 						'Follower'),
						   	   (9, 'Smart Seeker',						'Smart Seeker'), 
						   	   (10, 'Combi: POMCP & Follower',			'Ad. CR-POMCP Follower'), 
						   	   (11, 'N/A',								'N/A'), 
						   	   (12, 'Follower LastPos Exact',			'D. Follower'), 
						   	   (13, 'Highest Belief Follower POMCP',	'HB-CR-POMCP'), 
						   	   (14, 'Combi: Highest Bel. POCMP & Follower', 'Ad. HB-CR-POMCP Follower'), 
						   	   -- (15, 'Multi Seeker Highest Belief Explorer', 'Multi Seeker HB-CR-POMCP'); -- in theory changed 150427 to TwoSeeker
                               (15, 'Two Seeker Highest Belief Explorer', 'Two Seeker HB-CR-POMCP'),
                               (16, 'Multi Seeker Highest Belief Explorer', 'Multi Seeker HB-CR-POMCP'),
                               (17, 'Follower Sees-All',				'Follower S.All'), 
                               (18, 'Kalman Filter', 					'Kalman Filter'),
                               (19, 'Kalman Filter (only if obs.)', 	'Kalman Filter (obs.'),
                               (20, 'Particle Filter', 					'Particle Filter'),
                               (21, 'Particle Filter (only if obs.)', 	'Particle Filter (obs.)'),
                               (22, 'Particle Filter (always upd.)', 	'Particle Filter (upd.)'),
                               (23, 'Combi: Highest Belief PF & Follower', 	'Ad. HB-PF Follower'), -- always updates                               
                               (24, 'Multi Highest Belief Particle Filter', 'Multi HB-Particle Filter'); -- always updates

-- AG160506: update solver type
-- update SolverType set Name='Combi: Highest Belief PF & Follower',PubName='Ad. HB-PF Follower' where id=23;

-- SELECT * FROM SolverType;

DROP TABLE IF EXISTS MapName;
CREATE TABLE MapName (
	MapID INT NOT NULL, PRIMARY KEY(MapID),
	FileName VARCHAR(50),
    PubName VARCHAR(50) DEFAULT NULL -- publication name    
);


#insert values generated by scripts/solverMapsToSQL.py
INSERT INTO MapName (MapID,FileName) VALUES
(0,'map1_6x5_0o.txt'),
(1,'map2_6x5_1o.txt'),
(2,'map3_6x5_2o.txt'),
(3,'map4_6x5_2o.txt'),
(4,'map5_6x5_4o.txt'),
(5,'map1_40x40_1o.txt'),
(6,'map2_40x40_2o.txt'),
(7,'map3_40x40_3o.txt'),
(8,'map4_40x40_4o.txt'),
(9,'map5_40x40_5o.txt'),
(10,'testmapbig1.txt'),
(11,'testmapbig2.txt'),
(12,'map1_10x10_1o.txt'),
(13,'map2_10x10_2o.txt'),
(14,'map3_10x10_3o.txt'),
(15,'map4_10x10_4o.txt'),
(16,'map5_10x10.txt'),
(17,'map6_10x10.txt'),
(18,'map7_10x10.txt'),
(19,'mapbcn1.txt'),
(20,'mapbcn2.txt'),
(21,'mapbcn3.txt'),
(22,'mapbcn1a.txt'),
(23,'mapbcn1b.txt'),
(24,'mapbcn1c.txt'),
(25,'map1_20x20_0o.txt'),
(26,'map2_20x20_1o.txt'),
(27,'map3_20x20_2o.txt'),
(28,'map4_20x20_3o.txt'),
(29,'map5_20x20_4o.txt'),
(30,'map1_3x3_0o.txt'),
(31,'map2_3x3_1o.txt'),
(32,'map3_3x3_2o.txt'),
(33,'map1_5x5_0o.txt'),
(34,'map2_5x5_1o.txt'),
(35,'map3_5x5_2o.txt'),
(36,'map1_7x7_0o.txt'),
(37,'map2_7x7_1o.txt'),
(38,'map3_7x7_2o.txt'),
(39,'map1_40x40.txt'),
(40,'map2_40x40.txt'),
(41,'map3_40x40.txt'),
(42,'map4_40x40.txt'),
(43,'map5_40x40.txt'),
(44,'map1_20x20.txt'),
(45,'map2_20x20.txt'),
(46,'map3_20x20.txt'),
(47,'map4_20x20.txt'),
(48,'map5_20x20.txt'),
(49,'map1_17x17.txt'),
(50,'map2_17x17.txt'),
(51,'map3_17x17.txt'),
(52,'map4_17x17.txt'),
(53,'map1_15x15.txt'),
(54,'map2_15x15.txt'),
(55,'map3_15x15.txt'),
(56,'map4_15x15.txt'),
(57,'map1_12x12.txt'),
(58,'map2_12x12.txt'),
(59,'map3_12x12.txt'),
(60,'map4_12x12.txt'),
(61,'map1_10x10.txt'),
(62,'map2_10x10.txt'),
(63,'map3_10x10.txt'),
(64,'map4_10x10.txt'),
(65,'map1_7x7.txt'),
(66,'map2_7x7.txt'),
(67,'map3_7x7.txt'),
(68,'map1_6x5.txt'),
(69,'map2_6x5.txt'),
(70,'map3_6x5.txt'),
(71,'map4_6x5.txt'),
(72,'map5_6x5.txt'),
(73,'map1_5x5.txt'),
(74,'map2_5x5.txt'),
(75,'map3_5x5.txt'),
(76,'map1_3x3.txt'),
(77,'map2_3x3.txt'),
(78,'map3_3x3.txt'),
(79,'fme_place/map1_10x12.txt'),
(80,'fme_place/map1_12x14.txt'),
(81,'fme_place/map2_10x12.txt'),
(82,'fme_place/map2_12x14.txt'),
(83,'fme_place/map3_10x12.txt'),
(84,'fme_place/map3_12x14.txt'),
(85,'fme_place/map_fmep1_10x12.txt'),
(86,'fme_place/map_fmep1_12x14.txt'),
(87,'fme_place/map_fmep2_10x12.txt'),
(88,'fme_place/map_fmep2_12x14.txt'),
(89,'fme_place/map_fmep3_10x12.txt'),
(90,'fme_place/map_fmep3_12x14.txt'),
(91,'map1_10x12.txt'),
(92,'map1_12x14.txt'),
(93,'map2_10x12.txt'),
(94,'map2_12x14.txt'),
(95,'map3_10x12.txt'),
(96,'map3_12x14.txt'),
(97,'fme_place/map1_9x10.txt'),
(98,'fme_place/map2_9x10.txt'),
(99,'fme_place/map3_9x10.txt'),
(100,'map1_9x10.txt'),
(101,'map2_9x10.txt'),
(102,'map3_9x10.txt'),
(103,'map0_8x6.txt'),
(104,'map1_8x6.txt'),
(105,'map0_6x8.txt'),
(106,'map1_6x8.txt'),
(107,'map0_7x9.txt'),
(108,'map1_7x9.txt'),
(109,'map2_7x9.txt'),
(110,'map3_7x9.txt'),
(111,'mapbcn_full.txt'),
(112,'fme_place/map1_9x12.txt'),
(113,'fme_place/map2_9x12.txt'),
(114,'map1_9x12.txt'),
(115,'map2_9x12.txt'),
(116,'mapbcn4.txt'),
(117,'mapbcn5.txt'),
(118,'mapbcn6.txt'),
(119,'bcn_lab/fme2014_map4.txt'),
(120,'brl/brl29a.txt'),
(121,'brl/master29e.txt'),
(122,'brl/master29f.txt'),
(123,'bcn_lab/upc_campus_1m.txt'),
(124,'ext/nsh.txt'),
(125,'ext/museum.txt'),
(126, 'brl/master2015s.txt'), 
(127, 'brl/master2015s2.txt'),
(128,'brl/master2016full.txt'),
(129,'brl/master2016med.txt'),
(130,'brl/master2016.txt');



SET SQL_SAFE_UPDATES=0;
-- now update values to put a PubName
UPDATE MapName SET PubName='FME' WHERE FileName='bcn_lab/fme2014_map4.txt';
UPDATE MapName SET PubName='BRL' WHERE FileName='brl/brl29a.txt';
UPDATE MapName SET PubName='Tel. Square' WHERE FileName='brl/master29e.txt';
UPDATE MapName SET PubName='Room M.' WHERE FileName='brl/master29f.txt';
UPDATE MapName SET PubName='NSH' WHERE FileName='ext/nsh.txt';
UPDATE MapName SET PubName='Museum' WHERE FileName='ext/museum.txt';
UPDATE MapName SET PubName='Tel. Square M.' WHERE FileName='brl/master2015s.txt';
UPDATE MapName SET PubName='Tel. Square S.' WHERE FileName='brl/master2015s2.txt';
UPDATE MapName SET PubName='Tel. Square L.' WHERE FileName='brl/master2016med.txt';
UPDATE MapName SET PubName='Tel. Square XL' WHERE FileName='brl/master2016full.txt';

-- SELECT * FROM MapName;
